---
title: "Results"
output: html_document
date: "2025-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(flextable)
```

```{r}
data <- read.csv('data/CrohnD.csv')
```

## 1 Описательная статистика

Ниже представлены таблицы с описательной статистикой.
```{r}
library(officer)

statistics <- list(
  `__N/Nmiss` = ~paste0(sum(!is.na(.x)), "/", sum(is.na(.x))),
  `__Mean (SD)` = ~ifelse(sum(!is.na(.x)) == 0, "-", paste0(round(mean(.x, na.rm = TRUE), 2), " (", round(sd(.x, na.rm = TRUE), 2), ")")),
  `__Median` = ~ifelse(sum(!is.na(.x)) == 0, "-", median(.x, na.rm = TRUE) %>% round(2) %>% as.character()),
  `__Q1 - Q3` = ~ifelse(sum(!is.na(.x)) == 0, "-", paste0(quantile(.x, .25, na.rm = TRUE) %>% round(2), " - ", quantile(.x, .75, na.rm = TRUE) %>% round(2))),
  `__Min - Max` = ~ifelse(sum(!is.na(.x)) == 0, "-", paste0(min(.x, na.rm = TRUE) %>% round(2), " - ", max(.x, na.rm = TRUE) %>% round(2)))
)

data_pre <- data %>% 
  # select(treat, where(is.numeric), -c(rownames, ID)) %>% 
  group_by(treat) %>% 
  summarise(across(where(is.numeric) & !c(rownames, ID), statistics)) %>% 
  pivot_longer(!treat) %>% 
  separate(name, into = c("Variable", "Statistics"), sep="__") %>% 
  mutate(
    Statistics=str_remove(Statistics, "_"),
    treat=case_when(treat=="d1" ~ "Drug 1",
                    treat=="d2" ~ "Drug 2",
                    treat=="placebo" ~ "Placebo")
    ) %>%
  bind_rows(
    data %>% 
      mutate(treat="Total") %>% 
      group_by(treat) %>% 
      summarise(across(where(is.numeric) & !c(rownames, ID), statistics)) %>% 
      pivot_longer(!treat) %>% 
      separate(name, into = c("Variable", "Statistics"), sep="__") %>% 
      mutate(
        Statistics=str_remove(Statistics, "_"))
    ) %>%
  pivot_wider(names_from = "Variable", values_from = "value") %>% 
  relocate(treat, Statistics, age, weight, height, BMI, nrAdvE) %>% 
  rename(`Number of AE`=nrAdvE, `BMI (kg/m^2)`=BMI, `Height (cm)`=height, `Weight (kg)`=weight, `Age (years)`=age,
         `Treatment group`=treat)
  

final_table <- as_flextable(as_grouped_data(x=data_pre, groups = "Treatment group"))

border_style <- fp_border(color = "black", style = "solid", width = 1)
  
final_table <- add_footer_lines(final_table, "Abbreviations: N - not missing, Nmiss - missing, SD - standard deviation") %>%
  theme_box() %>% 
  separate_header() %>%
  bold(j=1, i=~!is.na(`Treatment group`), bold=TRUE, part = "body") %>% 
  bold(part = "header", bold = TRUE) %>% 
  colformat_double(i=~is.na(`Treatment group`), j="Statistics", digits=0, big.mark = "") %>% 
  align(i=~!is.na(`Treatment group`), align = "center") %>%
  align(align = "center", part = "body") %>% 
  align(align = "center", part = "header") %>% 
  align(j=1, i=~is.na(`Treatment group`), align = "left") %>% 
  valign(valign = "center", part = "all") %>% 
  bg(part = "header", bg = "#a9c9fc") %>% 
  bg(j=1, i=~!is.na(`Treatment group`), bg = "#EDEDED") %>% 
  border(border.top = border_style,
         border.bottom = border_style,
         border.left = border_style,
         border.right = border_style,
         part = "header") %>% 
  # merge_at(i=2, j=5:7) %>% 
  italic(part = "footer") %>% 
  set_table_properties(layout = "autofit", width = .9) %>% 
  set_caption("Таблица 1 – Описательная статистика количественных признаков", autonum = run_autonum(seq_id = "tab"), align_with_table=FALSE)

final_table
  
```
```{r}

data_tot <- data %>% 
      mutate(treat="Total")

sizes <- data_tot %>% 
  select(where(is.character), ID) %>%
  count(treat) %>%
  bind_rows(
    data %>% 
      select(where(is.character), ID) %>%
      count(treat)
  )

total_n <- sizes %>% 
  filter(treat=="Total") %>% 
  pull(n)

d1_n <- sizes %>% 
  filter(treat=="d1") %>% 
  pull(n)

d2_n <- sizes %>% 
  filter(treat=="d2") %>% 
  pull(n)

placebo_n <- sizes %>% 
  filter(treat=="placebo") %>% 
  pull(n)

data_count <- data %>% 
  select(where(is.character), ID) %>% 
  count(treat, country) %>% 
  group_by(treat) %>% 
  mutate(pct_group=(n/sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%")) %>% 
  ungroup() %>% 
  mutate(variable="Country") %>%
  rename(variable_cat=country) %>% 
  bind_rows(
    data %>% 
      select(where(is.character), ID) %>% 
      count(treat, sex) %>% 
      group_by(treat) %>% 
      mutate(pct_group=(n/sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%")) %>% 
      ungroup() %>% 
      mutate(variable="Sex") %>%
      rename(variable_cat=sex)
  ) %>%
  mutate(`n (%)` = paste0(n, " (", pct_group, ")"),
         treat=case_when(treat=="d1" ~ paste0("Drug 1","\n", "N = ", {{d1_n}}, "\n", "n (%)"),
                        treat=="d2" ~ paste0("Drug 2","\n", "N = ", {{d2_n}}, "\n", "n (%)"),
                        treat=="placebo" ~ paste0("Placebo","\n", "N = ", {{placebo_n}}, "\n", "n (%)"))) %>% 
  pivot_wider(id_cols = c(variable_cat, variable), names_from = treat, values_from = `n (%)`)
  

data_count_tot <- data_tot %>% 
  select(where(is.character), ID) %>% 
  count(treat, country) %>% 
  group_by(treat) %>% 
  mutate(pct_group=(n/sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%")) %>%
  ungroup() %>% 
  mutate(variable="Country") %>%
  rename(variable_cat=country) %>% 
  bind_rows(
    data_tot %>% 
      select(where(is.character), ID) %>% 
      count(treat, sex) %>% 
      group_by(treat) %>% 
      mutate(pct_group=(n/sum(n)) %>% round(4) %>% `*`(100) %>% str_c("%")) %>%
      ungroup() %>% 
      mutate(variable="Sex") %>%
      rename(variable_cat=sex)
  ) %>%
  mutate(`n (%)` = paste0(n, " (", pct_group, ")"),
         treat=paste0("Total","\n", "N = ", {{total_n}}, "\n", "n (%)")) %>% 
  pivot_wider(id_cols = c(variable_cat, variable), names_from = treat, values_from = `n (%)`)

data_final <- data_count %>% 
  bind_cols(data_count_tot %>% select(-c(variable_cat, variable))) %>% 
  relocate(variable, variable_cat) %>% 
  rename(Category = variable_cat)

final_table_cat <- as_flextable(as_grouped_data(x=data_final, groups = "variable"))

border_style <- fp_border(color = "black", style = "solid", width = 1)
  
final_table_cat <- add_footer_lines(final_table_cat, "Note: Percentages are based on the number of subjects in the corresponding group. \nAbbreviations: c1 - country 1, c2 - country 2, F - female, M - male.") %>%
  theme_box() %>% 
  separate_header() %>%
  bold(j=1, i=~!is.na(variable), bold=TRUE, part = "body") %>% 
  bold(part = "header", bold = TRUE) %>% 
  colformat_double(i=~is.na(variable), j="Category", digits=0, big.mark = "") %>% 
  align(i=~!is.na(variable), align = "center") %>%
  align(align = "center", part = "body") %>% 
  align(align = "center", part = "header") %>% 
  align(j=1, i=~is.na(variable), align = "left") %>% 
  valign(valign = "center", part = "all") %>% 
  bg(part = "header", bg = "#a9c9fc") %>% 
  bg(j=1, i=~!is.na(variable), bg = "#EDEDED") %>% 
  border(border.top = border_style,
         border.bottom = border_style,
         border.left = border_style,
         border.right = border_style,
         part = "header") %>% 
  # merge_at(i=2, j=5:7) %>% 
  italic(part = "footer") %>% 
  set_table_properties(layout = "autofit", width = .9)%>% 
  set_caption("Таблица 2 – Описательная статистика категориальных признаков", autonum = run_autonum(seq_id = "tab"), align_with_table=FALSE)

final_table_cat

```


## 2

```{r}

```

## 3

```{r}

```

## 4

```{r}

```

